# Generated by Django 3.1.14 on 2022-07-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vote',
            field=models.IntegerField(default=0, verbose_name='票数'),
        ),
    ]
