# Generated by Django 3.1.14 on 2022-08-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_id',
            field=models.CharField(default=1, max_length=1, primary_key=True, serialize=False),
        ),
    ]
